In [2]:
import numpy as np
import pandas as pd

In [3]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np
import pandas as pd

In [5]:
df=pd.read_csv(r"C:\Users\Hp\OneDrive\Desktop\Data Science\project\used_bike\Used_bikes.csv")

In [6]:
df

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power          brand  
0      First Owner   3.0  110.0            TVS  
1      First Owner   4.0  350.0  Royal Enfield  
2      First Owner   8.0  675.0        Triumph  
3      First Owner   4.0  180.0            TVS  
4      First Owner   3.0  150.0         Yamaha  
...            ...   ...    ...            ...  
32643  First Owner   4.0  100.0           Hero  
32644  First Owner   9.0  180.0            TVS  
32645  First Owner   6.0  220.0          Bajaj  
32646  First Owner  16.0  125.0           Hero  
32647  First Owner  13.0  150.0          Bajaj  

[32648 rows x 8 columns]

In [7]:
df.duplicated().sum()

np.int64(25324)

In [8]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [9]:
df["city"].unique()

array(['Ahmedabad', 'Delhi', 'Bangalore', 'Mumbai', 'Kalyan', 'Faridabad',
       'Mettur', 'Hyderabad', 'Kaithal', 'Gurgaon', 'Pune', 'Noida',
       'Nashik', 'Kochi', 'Allahabad', 'Samastipur', 'Nadiad', 'Lucknow',
       'Jaipur', 'Karnal', 'Gorakhpur', 'Vidisha', 'Hosur', 'Bagalkot',
       'Baripara', 'Agra', 'Dharwad', 'Vadodara', 'Jalandhar', 'Surat',
       'Chennai', 'Navi Mumbai', 'Gandhidham', 'Visakhapatnam',
       'Thrissur', 'Kolkata', 'Ernakulam', 'Barasat', 'Ghaziabad',
       'Bhubaneshwar', 'Amritsar', 'Bhopal', 'Hamirpur(hp)', 'Kottayam',
       'Arrah', 'Patiala', 'Ranga Reddy', 'Mandi', 'Ludhiana', 'Mandya',
       'Siliguri', 'Aurangabad', 'Kanpur', 'Bhilwara', 'Meerut', 'Rewari',
       'Ahmednagar', 'Wardha', 'Chandigarh', 'Ranchi', 'Panvel', 'Thane',
       'Jabalpur', 'Kota', 'Rohtak', 'Rajkot', 'Varanasi', '24 Pargana',
       'Banka', 'Nagpur', 'Banki', 'Pali', 'Chhatarpur', 'Katihar',
       'Mohali', 'Rudrapur', 'Coimbatore', 'Jajpur', 'Mysore', 'Adoni',

In [10]:
df["bike_name"].unique()  

array(['TVS Star City Plus Dual Tone 110cc',
       'Royal Enfield Classic 350cc', 'Triumph Daytona 675R',
       'TVS Apache RTR 180cc', 'Yamaha FZ S V 2.0 150cc-Ltd. Edition',
       'Yamaha FZs 150cc', 'Honda CB Hornet 160R  ABS DLX',
       'Hero Splendor Plus Self Alloy 100cc',
       'Royal Enfield Thunderbird X 350cc',
       'Royal Enfield Classic Desert Storm 500cc',
       'Yamaha YZF-R15 2.0 150cc', 'Yamaha FZ25 250cc',
       'Bajaj Pulsar NS200', 'Bajaj Discover 100M', 'Bajaj Discover 125M',
       'Bajaj Pulsar NS200 ABS', 'Bajaj Pulsar RS200 ABS',
       'Suzuki Gixxer SF 150cc', 'Benelli 302R 300CC',
       'Hero Splendor iSmart Plus IBS 110cc',
       'Royal Enfield Classic Chrome 500cc', 'Yamaha FZ V 2.0 150cc',
       'Hero Super Splendor 125cc', 'Honda CBF Stunner 125cc',
       'Bajaj Pulsar 150cc', 'Honda X-Blade 160CC ABS',
       'Bajaj Avenger 220cc', 'KTM RC 390cc', 'Honda CB Unicorn 150cc',
       'KTM Duke 200cc', 'Honda CBR 150R 150cc',
       'Royal Enfiel

In [11]:
df["price"].unique()

array([ 35000., 119900., 600000., ...,  65450.,  11400.,  61483.],
      shape=(1232,))

In [12]:
df["kms_driven"].unique()

array([17654., 11000.,   110., ..., 48587.,  3430.,  7127.], shape=(3722,))

In [13]:
dt={
    'First Owner':1,
    'Second Owner':2,
    'Third Owner':3,
    'Fourth Owner Or More':4
    }
df['owner']=df['owner'].map(dt)

In [14]:
df['owner'].unique()

array([1, 2, 3, 4])

In [15]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [16]:
import sklearn as kit

In [17]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [18]:
encoder=LabelEncoder()

In [19]:
output=encoder.fit_transform(df['brand'])

In [20]:
df['brand']=output

In [21]:
output.shape

(32648,)

In [22]:
output

array([19, 17, 20, ...,  1,  5,  1], shape=(32648,))

In [23]:
df.dtypes

bike_name      object
price         float64
city           object
kms_driven    float64
owner           int64
age           float64
power         float64
brand           int64
dtype: object

In [24]:
df.drop(['bike_name','city'],axis=1,inplace=True)

In [25]:
x=df.drop('price',axis=1)
y=df[['price']]

In [26]:
x

kms_driven  owner   age  power  brand
0         17654.0      1   3.0  110.0     19
1         11000.0      1   4.0  350.0     17
2           110.0      1   8.0  675.0     20
3         16329.0      1   4.0  180.0     19
4         10000.0      1   3.0  150.0     21
...           ...    ...   ...    ...    ...
32643     22000.0      1   4.0  100.0      5
32644      6639.0      1   9.0  180.0     19
32645     20373.0      1   6.0  220.0      1
32646     84186.0      1  16.0  125.0      5
32647     60857.0      1  13.0  150.0      1

[32648 rows x 5 columns]

In [27]:
y #dependent variable

price
0       35000.0
1      119900.0
2      600000.0
3       65000.0
4       80000.0
...         ...
32643   39000.0
32644   30000.0
32645   60000.0
32646   15600.0
32647   22000.0

[32648 rows x 1 columns]

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [30]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((26118, 5), (6530, 5), (26118, 1), (6530, 1))

In [31]:
x_train.head()
x_train.shape

(26118, 5)

In [32]:
y_train.head()
y_train.shape

(26118, 1)

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
lr=LinearRegression()

In [35]:
x_train.isnull()

kms_driven  owner    age  power  brand
17390       False  False  False  False  False
19014       False  False  False  False  False
16949       False  False  False  False  False
25968       False  False  False  False  False
380         False  False  False  False  False
...           ...    ...    ...    ...    ...
29802       False  False  False  False  False
5390        False  False  False  False  False
860         False  False  False  False  False
15795       False  False  False  False  False
23654       False  False  False  False  False

[26118 rows x 5 columns]

In [36]:
lr.fit(x_train,y_train)

LinearRegression()

In [37]:
print("Testing Score is:",lr.score(x_test,y_test))

Testing Score is: 0.7357003929631125


In [38]:
lr.predict(x_test)

array([[  9224.84776271],
       [ 31478.22431796],
       [ 15902.81986263],
       ...,
       [436350.09267399],
       [ 43670.09006732],
       [ 87083.77685838]], shape=(6530, 1))

In [39]:
pred=lr.predict(x_test)

In [40]:
pred

array([[  9224.84776271],
       [ 31478.22431796],
       [ 15902.81986263],
       ...,
       [436350.09267399],
       [ 43670.09006732],
       [ 87083.77685838]], shape=(6530, 1))

In [41]:
x_test.shape

(6530, 5)

In [42]:
y_test

price
28994   18000.0
31433   43000.0
17250   10000.0
13738   14227.0
24577   87000.0
...         ...
21858   20000.0
11813   25000.0
7033   670000.0
7406    46000.0
31555   70000.0

[6530 rows x 1 columns]

In [43]:
df

price  kms_driven  owner   age  power  brand
0       35000.0     17654.0      1   3.0  110.0     19
1      119900.0     11000.0      1   4.0  350.0     17
2      600000.0       110.0      1   8.0  675.0     20
3       65000.0     16329.0      1   4.0  180.0     19
4       80000.0     10000.0      1   3.0  150.0     21
...         ...         ...    ...   ...    ...    ...
32643   39000.0     22000.0      1   4.0  100.0      5
32644   30000.0      6639.0      1   9.0  180.0     19
32645   60000.0     20373.0      1   6.0  220.0      1
32646   15600.0     84186.0      1  16.0  125.0      5
32647   22000.0     60857.0      1  13.0  150.0      1

[32648 rows x 6 columns]

In [44]:
import joblib as jb

Loss Function 
. MSE
. MAE
. RMSE
. Huber loss

MSE


In [45]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [46]:
print("mse:-",mean_squared_error(y_test,pred))

mse:- 2301905401.2142873


In [47]:
# pred , y_test

RMSE

In [48]:
from sklearn.metrics import mean_squared_error
import math

In [49]:
print("rmse:-",math.sqrt(mean_squared_error(y_test,pred)))

rmse:- 47978.17630146322


In [50]:
print("by using numpy:-",np.sqrt(mean_squared_error(y_test,pred)))

by using numpy:- 47978.17630146322


In [51]:
y_test

price
28994   18000.0
31433   43000.0
17250   10000.0
13738   14227.0
24577   87000.0
...         ...
21858   20000.0
11813   25000.0
7033   670000.0
7406    46000.0
31555   70000.0

[6530 rows x 1 columns]

Huber Loss

#model Evalutaion
  .confusion matrix
  .Accuracy
  .precision
  .Recall
  .F1 Score 

In [52]:
from sklearn.metrics import confusion_matrix,f1_score,precision_score,recall_score

In [53]:
pred=(pred>0.5).astype(int).ravel()

In [54]:
pred

array([1, 1, 1, ..., 1, 1, 1], shape=(6530,))

In [55]:
confusion_matrix(y_test,pred)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], shape=(495, 495))

In [56]:
y

price
0       35000.0
1      119900.0
2      600000.0
3       65000.0
4       80000.0
...         ...
32643   39000.0
32644   30000.0
32645   60000.0
32646   15600.0
32647   22000.0

[32648 rows x 1 columns]

In [58]:
from sklearn.ensemble import GradientBoostingRegressor

In [59]:
gd=GradientBoostingRegressor()

In [60]:
x_train.isnull()

kms_driven  owner    age  power  brand
17390       False  False  False  False  False
19014       False  False  False  False  False
16949       False  False  False  False  False
25968       False  False  False  False  False
380         False  False  False  False  False
...           ...    ...    ...    ...    ...
29802       False  False  False  False  False
5390        False  False  False  False  False
860         False  False  False  False  False
15795       False  False  False  False  False
23654       False  False  False  False  False

[26118 rows x 5 columns]

In [61]:
gd.fit(x_train,y_train)

c:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\ensemble\_gb.py:672: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?


GradientBoostingRegressor()

In [62]:
pip install xgboost

   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.5/150.0 MB 213.7 kB/s eta 0:11:40
   ---------------------------------------- 0.5/150.0 MB 213.7 kB/s eta 0:11:40
   ---------------------------------------- 0.5/150.0 MB 213.7 kB/s eta 0:11:40
   ---------------------------------------- 0.5/15


[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
