In [5]:
%pip install numpy

  Using cached numpy-2.2.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    ----------------


[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

In [9]:
lst=list(range(1,25))
arr=np.array(lst)
print(type(arr))
print(type(lst))

<class 'numpy.ndarray'>
<class 'list'>


Creating numpy array

In [11]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [17]:
list=list(range(1,10))
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


Arrange()- used to create the array

In [20]:
arr=np.arange(1,25)
arr #Single dimensional array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [23]:
#2D array
arr=np.zeros((3,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#create 2D array
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
#creating 3D array (2 blocks,3 rows,4columns)
arr=np.array([[[1,2,3,4],[5,6,7,8],[9,0,1,2]],[[12,43,44,76],[89,6,5,8],[76,56,7,8]]])
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9,  0,  1,  2]],

       [[12, 43, 44, 76],
        [89,  6,  5,  8],
        [76, 56,  7,  8]]])

In [31]:
arr=np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#linshape() is used to create array in the equal intervals
#reshape() is used for re shape  the array
arr=np.linspace(1,20,5).reshape(5,1)
arr

array([[ 1.  ],
       [ 5.75],
       [10.5 ],
       [15.25],
       [20.  ]])

In [37]:
arr=np.arange(0,30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [38]:
arr.shape

(5, 6)

In [39]:
arr.reshape(3,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [ ]:
#Random initialization
#randint is used to give range
arr=np.random.randint(1,5,9)
arr

array([1, 1, 3, 3, 2, 1, 4, 2, 1], dtype=int32)

In [50]:
arr=np.random.random(10)
arr

array([0.20025286, 0.75211149, 0.88587706, 0.51872764, 0.15066199,
       0.8047074 , 0.68515029, 0.56241521, 0.96616793, 0.58265409])

In [52]:
arr=np.random.randint(10)
arr

7

In [54]:
arr=np.arange(60).reshape(10,6)
arr
arr.dtype
arr.ndim
arr.size
arr.shape

(10, 6)

In [ ]:
arr.flatten()
#flatten() is used to convert 2D/3D to 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [58]:
lst=[1,3,643,45]
arr=np.array(lst)
arr.shape

(4,)

In [59]:
arr.T.shape

(4,)